turn on typescript + jest checks (#23)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -74,9 +74,27 @@ jobs:
 
       - name: Build render-opengraph
         working-directory: ./packages/render-opengraph
-        run: wasm-pack build --target web
+        run: |
+          wasm-pack build --target web
+          rm pkg/render_opengraph_bg.wasm.d.ts
 
       - run: yarn workspace nouns-agora-backend run generate
+
+      - name: Typescript
+        working-directory: ./packages/backend
+        run: yarn tsc --noEmit
+
+      - name: Run Test
+        working-directory: ./packages/backend
+        run: yarn test
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Backend Tests
+          path: ./packages/backend/dist/reports/junit.xml
+          reporter: jest-junit
 
       - run: yarn workspace nouns-agora-backend run build-worker
 
